line_length: 140

opt_in_rules:
 - file_header
 - implicit_return

disabled_rules:
 - trailing_comma

file_header:
  severity: warning
  forbidden_pattern: ".?"

shorthand_operator: warning
force_cast: warning
force_try: warning

identifier_name:
 
